"""empty message

Revision ID: e715f3c935e7
Revises: 
Create Date: 2022-04-03 08:52:18.564008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e715f3c935e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_category', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('provisor', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('medicine',
    sa.Column('id_medicine', sa.Integer(), nullable=False),
    sa.Column('name_medicine', sa.String(length=45), nullable=False),
    sa.Column('manufacturer', sa.String(length=45), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock_number', sa.Integer(), nullable=False),
    sa.Column('demand_number', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id_category'], ),
    sa.PrimaryKeyConstraint('id_medicine')
    )
    op.create_table('order',
    sa.Column('id_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_order', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('medicine_in_order',
    sa.Column('id_medicine_in_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_medicine', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicine'], ['medicine.id_medicine'], ),
    sa.ForeignKeyConstraint(['id_order'], ['order.id_order'], ),
    sa.PrimaryKeyConstraint('id_medicine_in_order')
    )
    op.create_table('shopping_cart',
    sa.Column('id_shopping_cart', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_medicine', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicine'], ['medicine.id_medicine'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_shopping_cart')
    )
    op.create_table('wish_list',
    sa.Column('id_wish_list', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_medicine', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicine'], ['medicine.id_medicine'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_wish_list')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish_list')
    op.drop_table('shopping_cart')
    op.drop_table('medicine_in_order')
    op.drop_table('order')
    op.drop_table('medicine')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
